package middleware

import (
	"log/slog"
	"time"

	"github.com/gin-contrib/requestid"
	"github.com/gin-gonic/gin"
)

const (
	// RequestIDHeader is the HTTP header used to propagate the request ID.
	RequestIDHeader = "X-Request-Id"
)

// RequestID generates a unique request ID for every request, sets it in the
// gin context and the response header. Reuses an incoming X-Request-Id header
// if one is provided (e.g. from a load balancer).
func RequestID() gin.HandlerFunc {
	return requestid.New(
		requestid.WithCustomHeaderStrKey(RequestIDHeader),
	)
}

// RequestLogger logs each completed request with timing and the request ID
// generated by the RequestID middleware.
func RequestLogger() gin.HandlerFunc {
	return func(c *gin.Context) {
		start := time.Now()
		c.Next()
		latency := time.Since(start)

		slog.Info("request",
			"request_id", requestid.Get(c),
			"method", c.Request.Method,
			"path", c.Request.URL.Path,
			"status", c.Writer.Status(),
			"latency_ms", latency.Milliseconds(),
			"ip", c.ClientIP(),
		)
	}
}
