// Code generated by ent, DO NOT EDIT.

package backenduser

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the backenduser type in the database.
	Label = "backend_user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBackendUserID holds the string denoting the backend_user_id field in the database.
	FieldBackendUserID = "backend_user_id"
	// FieldBackendToken holds the string denoting the backend_token field in the database.
	FieldBackendToken = "backend_token"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeBackend holds the string denoting the backend edge name in mutations.
	EdgeBackend = "backend"
	// Table holds the table name of the backenduser in the database.
	Table = "backend_users"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "backend_users"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_backend_users"
	// BackendTable is the table that holds the backend relation/edge.
	BackendTable = "backend_users"
	// BackendInverseTable is the table name for the Backend entity.
	// It exists in this package in order to avoid circular dependency with the "backend" package.
	BackendInverseTable = "backends"
	// BackendColumn is the table column denoting the backend relation/edge.
	BackendColumn = "backend_backend_users"
)

// Columns holds all SQL columns for backenduser fields.
var Columns = []string{
	FieldID,
	FieldBackendUserID,
	FieldBackendToken,
	FieldEnabled,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "backend_users"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"backend_backend_users",
	"user_backend_users",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// BackendUserIDValidator is a validator for the "backend_user_id" field. It is called by the builders before save.
	BackendUserIDValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the BackendUser queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBackendUserID orders the results by the backend_user_id field.
func ByBackendUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBackendUserID, opts...).ToFunc()
}

// ByBackendToken orders the results by the backend_token field.
func ByBackendToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBackendToken, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByBackendField orders the results by backend field.
func ByBackendField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBackendStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newBackendStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BackendInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, BackendTable, BackendColumn),
	)
}
