// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Backend is the predicate function for backend builders.
type Backend func(*sql.Selector)

// BackendUser is the predicate function for backenduser builders.
type BackendUser func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
